include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/*.g.dart
    - tenant-manager/**
    - tools/**
    - lib/data/network/**

linter:
  rules:
    sort_pub_dependencies: false
    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    prefer_double_quotes: false

    # Good packages document everything
    # public_member_api_docs: true

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    # Back to the 120s
    lines_longer_than_120_chars: true

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false